name: konnektor
channels:
  - conda-forge
dependencies:
  - python
  - pip
  #Test
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-xdist
  - coverage
  - mypy
  - nbval
  #Typing
  - gufe
  - typing-extensions
  # Sci
  - numpy <2.3  # TypeError: assert_array_almost_equal() got an unexpected keyword argument 'x'
  - scipy
  - networkx
  - scikit-learn
  - scikit-mol>=0.5.5  # https://github.com/EBjerrum/scikit-mol/pull/68
  - dill
  # Chem
  - rdkit==2024.03.5
  # Vis
  - ipycytoscape
  # docs
  - sphinx<7
  - myst-parser
  - pydata-sphinx-theme
  - tqdm
  - nbsphinx
  - nbsphinx-link

  - pip:
    - dill
    - scikit-mol
