name: konnektor-docs
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - typing-extensions
  - numpy
  - networkx
  - gufe >=1.7
  - rdkit==2024.03.5
  - ipycytoscape
  - myst-parser
  - pydata-sphinx-theme
  - tqdm
  - pip:
    - git+https://github.com/OpenFreeEnergy/ofe-sphinx-theme@a45f3edd5bc3e973c1a01b577c71efa1b62a65d6
